config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('order/', include("order.urls")),
    path('delivery/', include("delivery.urls")),

    path('tinymce/', include('tinymce.urls')),

    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


import debug_toolbar
urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

delivery/urls.py
from django.urls import path
from .views import  load_communes, delivery_cost 
app_name ='delivery'
urlpatterns = [
   path('load-communes/', load_communes, name='load_communes'),
   path('delivery_cost/', delivery_cost, name='delivery_cost'),
   #  path('vapecity/', views.vapecity, name='vapecity'),
   #  path('contact/', views.ContactView.as_view(), name='ContactView'),
]

main/urls.py
from django.urls import path
from .views import IndexView, ProductDetailView, ProductsView, new_product_list, redirect_to_shop_view, CategoryProductsView, is_major
app_name ='main'
urlpatterns = [
   path('', IndexView.as_view(), name='IndexView'),
   path('produits', ProductsView.as_view(), name='Products'),
   path('produits/', redirect_to_shop_view, name='redirect_to_shop_view'),
   path('is_major/', is_major, name='is_major'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-cat'),
   path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-cat'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-sub-cat'),
   path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-sub-cat'),
   path('produits/new', new_product_list, name='prod-new'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-sub-cat'),
   path('produits/produit/<slug:slug>/', ProductDetailView.as_view(), name='productDetail'),
   
   #  path('vapecity/', views.vapecity, name='vapecity'),
   #  path('contact/', views.ContactView.as_view(), name='ContactView'),
]

order/urls.py
from django.urls import path
from .views import CartView, cart_detail, cart_add_one_product, cart_add, cart_remove, order_create, admin_order_detail ,admin_order_pdf, order_create_one_product

app_name = 'order'

urlpatterns = [
   # path('', CartView.as_view(), name='CartView'),
   path('cart', cart_detail, name='cart_detail'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   path('commander', order_create, name='order_create'),
   path('ajouter-au-panier<int:product_id>/', cart_add_one_product, name='cart_add_one_product'),
   path('acheter/<int:product_id>/', order_create_one_product, name='order_create_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
   path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),

]

order/models.py
from django.db import models

# Create your models here.

from main.models import Product
class Order(models.Model):
    
    first_name  = models.CharField(verbose_name="Nom" , max_length=50, null=True, blank=True)
    last_name   = models.CharField(verbose_name="Prenom" , max_length=50, null=True, blank=True)
    addresse    = models.CharField(verbose_name="Adresse" , max_length=250, null=True, blank=True)
    phone       = models.CharField(verbose_name="Téléphone" , max_length=25)
    email       = models.EmailField(null=True, blank=True)
    wilaya      = models.CharField(  max_length=50, null=True, blank=True)
    commune     = models.CharField(  max_length=50, null=True, blank=True)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    birth_date  = models.DateField(verbose_name="Date de naissance")
    note        = models.TextField(blank=True, null=True)
    paid        = models.BooleanField(default=False)
    confirmer   = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Commande"
        ordering = ('-created',)

    def __str__(self):
        return f'commande N°:  {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order    = models.ForeignKey(Order,related_name='items', verbose_name=("Commande"), on_delete=models.CASCADE)
    product  = models.ForeignKey(Product, verbose_name=("Commande"), on_delete=models.CASCADE)
    price    = models.DecimalField( max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default = 1 )

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

order/forms.py
from django import forms 
from django.forms import NumberInput
# from django.core import validators
from .models import Order
from delivery.models import Commune

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField( min_value=1, widget=NumberInput(attrs={'class': 'form-control text-center','value': 1, 'max':20 }))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class CartAddProductQuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)


class OrderCreateForm(forms.ModelForm):
    # quantity = forms.IntegerField(min_value=1)
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'addresse', 'birth_date', 'email', 'phone', 'wilaya', 'commune', 'note']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['wilaya'] = forms.ModelChoiceField(queryset=Wilaya.objects.all()) 
        # self.fields['commune'] = forms.ModelChoiceField(queryset=Commune.objects.all()) 

        self.fields['commune'].queryset = Commune.objects.none()
        self.fields['quantity'] = forms.IntegerField(min_value=1)

        if 'wilaya' in self.data:
            try:
                wilaya_id = int(self.data.get('wilaya'))
                self.fields['commune'].queryset = Commune.objects.filter(wilaya_id=wilaya_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif not 'wilaya' in self.data:
            self.fields['commune'].queryset = Commune.objects.none()

class OrderFormWithOutQuantity(OrderCreateForm):
    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)

order/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import TemplateView
from django.views.decorators.http import require_POST
from .cart import Cart
from main.models import Product
from .models import  OrderItem, Order
from delivery.models import Wilaya
from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CartAddProductForm, OrderCreateForm, OrderFormWithOutQuantity
from django.template.loader import render_to_string
# import weasyprint

class CartView(TemplateView):
    template_name = "cart.html"
    

# class CheckoutView(TemplateView):
#     template_name = "checkout.html"

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
        # print('baskets details', list(cart))
        # print('Wach ahda item details', item)
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(initial={ 'quantity': item['quantity']})
    #     item['total'] = item['product'].price * item['quantity']
    #     items.append(item)
    #     products.append(item['product'])
    context = {
        'cart': cart,
        # 'coupon_apply_form': coupon_apply_form
    }
    return render(request, 'cartView.html', context)

def cart_add_one_product(request, product_id):
    cart = Cart(request)
    # Get the product that we want to add
    product = get_object_or_404(Product, id= product_id, available=True)
    
    if product:
        quantity = 1
        cart.add_one(
                product=product,
                quantity=quantity,
        )
        return redirect('order:cart_detail')
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    try:
        if form.is_valid():
                cd = form.cleaned_data
                cart.add(
                    product=product,
                    quantity=cd['quantity'],
                    override_quantity=cd['override']
                )
                print('the Cart two', cart)
                return redirect('order:cart_detail')
    except:
        return redirect('/')



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('order:cart_detail')


def order_create_one_product(request,product_id=None):
 
    form = OrderCreateForm()
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        form = OrderCreateForm(request.POST)
        print(
                'le FORMULAIRE', form
                )
        if form.is_valid():
            cd = form.cleaned_data
            quantity=cd['quantity']
            order = form.save()
            print('le formulaire est valid', quantity)
            # print('ORDER ITEM', order.quantity)
            OrderItem.objects.create(order=order,product=product,price=product.price,quantity=quantity)
                # order_created.delay(order.id)
                # order = Order.objects.get(id=order_id)
                # subject = f'Commande N°: {order.id}'
                # message = f'Chére {order.first_name},\n\n' \
                #         f'vous avez passer une commande avec succés' \
                #         f'votre identifiant de commande est le: {order.id}'
                # mail_sent = send_mail(subject, message, 'inter.taki@gmail.com',[order.email])
            return render(request, 'created.html', {'order': order})
            # print('ORDER ITEM')
            # return render(request, 'created.html', {'order': order})
        else:
            # print('yhnooo')
            return redirect(reverse('main:IndexView'))
    return render(request, 'productDetail.html', { 'form' : form})




def order_create(request):
    cart = Cart(request)
    wilayas= Wilaya.objects.all().order_by('name') 
    form = OrderFormWithOutQuantity()
    print('INIT FORM', OrderFormWithOutQuantity())
    if cart.__len__() :
        print('request', request.method)
        if request.method == 'POST':
            form = OrderFormWithOutQuantity(request.POST)
            if form.is_valid():
                print('le formulaire est valid')
                order = form.save()
                # try:
                print('carte ========>',cart)
                for item in cart:
                    OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
                cart.clear()
                return render(request, 'created.html', {'order': order})
    else: 
        return redirect(reverse('main:IndexView'))
    return render(request, 'order_create.html', {'cart':cart, 'form' : form, 'wilayas': wilayas})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order_detail.html', {'order': order})

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order_pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    # weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])
    # # ajouter le style plus t ard erreur ???
    # weasyprint.HTML(string=html).write_pdf(response)
    return response

order/templates/cartView.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% load static %}
  
<section class="cart-section">
    <div class="auto-container">

        <!--Cart Outer-->
        <div class="cart-outer">
            <div class="table-outer">
                <table class="cart-table">
                    <thead class="cart-header">
                        <tr>
                            <th>Aperçu</th>
                            <th class="prod-column">Produit</th>
                            <th class="price">Prix</th>
                            <th>Quantité</th>
                            <th>Total</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                                <tr>
                                    <td class="prod-column">
                                        <div class="column-box">
                                            <figure class="prod-thumb"><a href="{{product.get_absolute_url}}">
                                                   
                                                {% if product.photo1 %}
                                                    {% if product.photo1.url %}
                                                        <img style="  width: 100%; height: auto;" src="{{product.photo1.url}}" alt="{{product.name}}">
                                                    {% else %}
                                                        <img style="  width: 100%; height: auto;" src="{% static 'no-photo.png' %}" alt="{{product.name}}">
                                                    {% endif %}
                                                {% endif %}
                                            </a></figure>
                                        </div>
                                    </td>
                                    <td><h4 class="prod-title">{{product.name}}</h4></td>
                                    <td class="sub-total">{{item.price}}</td>
                                    
                                    <td class="qty"><div class="item-quantity"><div class="input-number">
                                        <form action="{% url 'order:cart_add' product.id %}" method="post">
                                                {% csrf_token %}
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                            <span class="qty-up">
                                                <button style="height:20px;width: 25px;border: none;border-right: 1px solid #E4E7ED;border-top: 1px solid #E4E7ED;background-color: #fff;" type="submit">
                                                    +
                                                </button>
                                            </span>
                                            <span class="qty-down">
                                                <button style="height:20px;width: 25px;border: none;border-right: 1px solid #E4E7ED;border-bottom: 1px solid #E4E7ED;background-color: #fff;" type="submit">
                                                -
                                                </button>
                                            </span>
                                        </form>
                                    </div></div></td>
                                    <td class="total-price">{{item.total_price}}</td>
                                    <td>
                                        <form action="{% url 'order:cart_remove' product.id %}" method="post">
                                            {% csrf_token %}

                                            <button type="submit" style="border: none;background-color: #fff;" class="remove-btn">
                                                <span class="fa fa-trash-o"></span>
                                            </button>
                                        </form>
                                    
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row clearfix " style="margin-top: 15px;">
                <div class="column col-lg-7 col-md-5 col-sm-12">
                </div>
                <div class="column col-lg-5 col-md-7 col-sm-12 mt-5">
                    <!--Totals Table-->
                    <ul class="totals-table">
                        <li><h3> Total Panier</h3></li>
                        <li class="clearfix total"><span class="col">Total</span><span class="col price">{{cart.get_total_price}} DZD</span></li>
                        <li class="text-right">
                            <a class="theme-btn proceed-btn" href="{% url 'order:order_create' %}">
                                Procéder au paiement
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</section>
<!--End Cart Section-->

{% endblock content %}

order/templates/created.html
{% extends "base.html" %}
{% load static %}
{% static "img" as baseUrl %}

{% block content %}
	<!-- Title Page -->
	<div id="breadcrumb" class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-12">
					<h3 class="breadcrumb-header">PANIER</h3>
					<ul class="breadcrumb-tree">
						<li><a href="{% url 'main:IndexView' %}">Accueil</a></li>
						<li class="active">Detail de commande </li>
					</ul>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>



    <!--================Cart Area =================-->
	<section class="order_details section_gap mb-5">
		<div class="container">
			<h3 class="title_confirmation">Merci, Votre commande a été effectué avec succée.</h3>
			<div class="row order_d_inner">
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Commande Infos</h4>
						<ul class="list">
							<li><a href="#"><span>Commande Numéro </span> : {{ order.id }}</a></li>
							<li><a href="#"><span>Date</span> : {{order.created}}</a></li>
							<li><a href="#"><span>Total</span> : {{ item.get_cost }} DA</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Livraison info </h4>
						<ul class="list">
							<li><a href="#"><span>Wilaya</span> : {{ order.wilaya }} </a></li>
							<li><a href="#"><span>Commune</span> : {{ order.commune }} </a></li>
							<li><a href="#"><span>Adresse</span> : {{ order.addresse }} </a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="order_details_table mb-5">
				<h2>Commande Details</h2>
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Produit</th>
								<th scope="col">Quantité</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody>
						{% for item in order.items.all %}
							<tr>
								<td><p>{{ item.product.name }}</p></td>
								<td><h5>x {{ item.quantity }}</h5></td>
								<td><p> {{ item.price }} DA</p></td>
							</tr>
						{% endfor %}
							<tr>
								<td>
									<h4>Sous-Total</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>{{ order.get_total_cost }} DA</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Livraison</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>600 DA</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Total</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>{{ order.get_total_cost }}</p>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
    <!--================End Cart Area =================-->


{% endblock content %}

order/templates/order_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  
		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Validation</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Validation</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<form id="order_form" action="" method="post" data-communes-url="{% url 'delivery:load_communes' %}">
						{% csrf_token %}
						<div class="col-md-7">
							<!-- Billing Details -->
							<div class="billing-details">
								<div class="section-title">
									<h3 class="title">Coordonnées</h3>
								</div>
								<div class="form-group">
									<input class="input" type="text" name="first_name" placeholder="nom (اللقب)">
								</div>
								<div class="form-group">
									<input class="input" type="text" name="last_name" placeholder="prenom (الاسم)">
								</div>
								<div class="form-group">
									<input class="input" type="text" name="addresse"placeholder="addresse ( العنوان)">
								</div>
								<div class="form-group">
									<input class="input" type="email" name="email" placeholder="Email">
								</div>
								
								<div class="form-group">
									<select class="input" name="wilaya" id="wilayaId"  required>
										<option class="option" value='' selected>Wilaya ( الولاية)</option>
										{% for wilaya in wilayas %}
											<option class="option" data-price={{wilaya.price}} value={{wilaya.id}}>{{wilaya.name}}</option>
										{% endfor %}
									</select>
								</div>
								
								<div class="form-group">
									<select class="input" name="commune" id="communesId" required>
										<option class="option" value='' selected>Commune (البلدية)</option>
										{% for commune in communes %}
											<option class="option" value={{commune.id}}>{{commune.name}}</option>
										{% endfor %}
									</select>
								</div>
								
								<div class="form-group">
									<input class="input" type="tel" name="phone" placeholder="Téléphone (رقم الهاتف)">
								</div>
								<div class="form-group">
									<label for="birth_date">date de naissance (تاريخ الميلاد)</label>
									<input class="input" type="date" name="birth_date" placeholder="date de naissance (تاريخ الميلاد)">
								</div>
								
							</div>
							<!-- /Billing Details -->
							<!-- Order notes -->
							<div class="order-notes">
								<textarea class="input" name="note" placeholder="Order Notes"></textarea>
							</div>
							<!-- /Order notes -->
						</div>
						<!-- Order Details -->
						<div class="col-md-5 order-details">
							<div class="section-title text-center">
								<h3 class="title">Votre Commande</h3>
							</div>
							<div class="order-summary">
								<div class="order-col">
									<div><strong>PRODUCT</strong></div>
									<div><strong>TOTAL</strong></div>
								</div>
								<div class="order-products">
										{% with total_items=cart|length %}
										{% if total_items > 0 %}
											{% for item in cart %}
												{% with product=item.product %}
												<div class="order-col">
													<div>{{item.quantity}} x {{product.name}}</div>
													<div>{{item.price}} DZD</div>
												</div>
												{% endwith %}
										{% endfor %}
										
										{% else %}
											Vou n'avez pas de produit dans votre panier
										{% endif %}
										{% endwith %}
								</div>
								<div class="order-col">
									<div>Livraison</div>
									<div id="deliveryCost"><strong>Disponible</strong></div>
								</div>
								<div class="order-col">
									<div><strong>TOTAL</strong></div>
									<div><strong class="order-total">{{cart.get_total_price}} DZD</strong></div>
								</div>
							</div>
							<div class="payment-method">
							<button type="submit" class="primary-btn order-submit btn-block">Confirmer Ma Commande</button>
						</div>
						<!-- /Order Details -->
					</form>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% endblock content %}

order/templates/order_detail.html
{% extends "admin/base_site.html" %}

{% block title %}
    Order {{ order.id }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index'%}">Home</a> &rsaquo;
        <a href="{% url 'admin:order_order_changelist' %}">Commandes</a>
    </div>
{% endblock %}

{% block content %}
    <h1>Commande {{ order.id }}</h1>
        <ul class="object-tools">
            <li>
            <a href="#" onclick="window.print();">Imprimer</a>
            </li>
        </ul>
    <table>
            <tr>
                <th>Crée</th>
                <td>{{ order.created }}</td>
            </tr>
            <tr>
                    <th>Client</th>
                    <td>{{ order.first_name }} {{ order.last_name }}</td>
            </tr>
            <tr>
                <th>E-mail</th>
                <td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
            </tr>
            <tr>
            <th>Adresse</th>
                <td>
                    {{ order.addresse }}
                </td>
            </tr>
            <tr>
                <th>Wilaya</th>
                <td>
                    {{ order.wilaya.name }}
                </td>
            </tr>

            <tr>
                <th>Livraison</th>
                <td>
                    {{ order.wilaya.price }}
                </td>
            </tr>

            <tr>
                <th>Commune</th>
                <td>
                    {{ order.commune.name }}
                </td>
            </tr>
            {% if order.coupon %}
                <tr>
                    <th>Coupon:</th>
                    <td>{{order.coupon.code}}</td>
                </tr>
                <tr>
                    <th>Réduction:</th>
                    <td>{{order.discount_amount}} DA</td>
                </tr>
            {% endif %}
            <tr>
                <th>Prix total</th>
                <td>{{ order.get_total_cost_without_discount}} DA</td>
            </tr>
            {% if order.coupon %}
            <tr>
                <th>Prix total après réduction</th>
                <td>{{order.get_total_cost}}</td>
            </tr>
            {% endif %}
            <tr>
                <th>Status</th>
                <td>{% if order.paid %}Payée{% else %}Non payée{% endif %}</
            td>
            </tr>
    </table>
       <div class="module">
            <h2>Produits achetés</h2>
        <table style="width:100%">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>{{ item.product.name }}</td>
                <td class="num">${{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">${{ item.get_cost }}</td>
            </tr>
        {% endfor %}
            <tr class="total">
                <td colspan="3">Total</td>
                <td class="num">${{ order.get_total_cost_without_discount }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}