config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('order/', include("order.urls")),
    path('delivery/', include("delivery.urls")),

    path('tinymce/', include('tinymce.urls')),

    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


import debug_toolbar
urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

delivery/urls.py
from django.urls import path
from .views import  load_communes, delivery_cost 
app_name ='delivery'
urlpatterns = [
   path('load-communes/', load_communes, name='load_communes'),
   path('delivery_cost/', delivery_cost, name='delivery_cost'),
   #  path('vapecity/', views.vapecity, name='vapecity'),
   #  path('contact/', views.ContactView.as_view(), name='ContactView'),
]

main/urls.py
from django.urls import path
from .views import IndexView, ProductDetailView, ProductsView, new_product_list, redirect_to_shop_view, CategoryProductsView, is_major
app_name ='main'
urlpatterns = [
   path('', IndexView.as_view(), name='IndexView'),
   path('produits', ProductsView.as_view(), name='Products'),
   path('produits/', redirect_to_shop_view, name='redirect_to_shop_view'),
   path('is_major/', is_major, name='is_major'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-cat'),
   path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-cat'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-sub-cat'),
   path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-sub-cat'),
   path('produits/new', new_product_list, name='prod-new'),
   # path('produits/<slug:category_slug>/', product_list, name='prod-by-sub-cat'),
   path('produits/produit/<slug:slug>/', ProductDetailView.as_view(), name='productDetail'),
   
   #  path('vapecity/', views.vapecity, name='vapecity'),
   #  path('contact/', views.ContactView.as_view(), name='ContactView'),
]

order/urls.py
from django.urls import path
from .views import CartView, cart_detail, cart_add_one_product, cart_add, cart_remove, order_create, admin_order_detail ,admin_order_pdf, order_create_one_product

app_name = 'order'

urlpatterns = [
   # path('', CartView.as_view(), name='CartView'),
   path('cart', cart_detail, name='cart_detail'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   path('commander', order_create, name='order_create'),
   path('ajouter-au-panier<int:product_id>/', cart_add_one_product, name='cart_add_one_product'),
   path('acheter/<int:product_id>/', order_create_one_product, name='order_create_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
   path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),

]

main/models.py
from django.db import models
from django.urls import reverse
from tinymce.widgets import TinyMCE
from tinymce import models as tinymce_models
# Create your models here.

class Category(models.Model):
    name = models.CharField( max_length=150, verbose_name='Nom')
    slug = models.SlugField( max_length=150, verbose_name='URL')
    # pixel = models.TextField(verbose_name='Facebook Pixel', blank=True, null=True)

    class Meta:
        ordering = ('id',)
        verbose_name = 'Catégorie'
        verbose_name_plural = '1. Categories'

    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("main:prod-by-cat", args=[self.slug])

class TreeCategory(models.Model):
    name = models.CharField( max_length=150, verbose_name='Nom')
    slug = models.SlugField( max_length=150, verbose_name='URL')
    category = models.ForeignKey(Category, verbose_name="Catégorie",related_name="trees" ,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('id',)
        verbose_name = 'Branche de Catégorie'
        verbose_name_plural = '2. Branches de Catégorie'
    
    def get_absolute_url(self):
        return reverse("main:prod-by-sub-cat", args=[self.slug])


class SubCategory(models.Model):
    name = models.CharField( max_length=150, verbose_name='Nom')
    slug = models.SlugField( max_length=150, verbose_name='URL')
    icon = models.FileField(upload_to='sous_cat/icons', max_length=100, verbose_name="icon de la Catégorie")
    tree = models.ForeignKey(TreeCategory, verbose_name="Branche de Catégorie",related_name="sub_categories" ,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('id',)
        verbose_name = 'Sous Catégorie'
        verbose_name_plural = '3. Sous Catégorie'
    
    def get_absolute_url(self):
        return reverse("main:prod-by-sub-cat", args=[self.slug])


# class SubCategory(models.Model):
#     name = models.CharField( max_length=150, verbose_name='Nom')
#     slug = models.SlugField( max_length=150, verbose_name='URL')
#     icon = models.FileField(upload_to='sous_cat/icons', max_length=100, verbose_name="icon de la Catégorie")
#     category = models.ForeignKey(Category, verbose_name="Catégorie",related_name="sub_categories" ,on_delete=models.CASCADE)






class Product(models.Model):
    name = models.CharField( max_length=150, verbose_name='Nom')
    slug = models.SlugField( max_length=150, verbose_name='URL', unique=True)
    sous_category = models.ForeignKey(SubCategory, verbose_name="Sous Catégorie",related_name="products" ,on_delete=models.CASCADE)
    description = tinymce_models.HTMLField(verbose_name='Déscription', blank=True, null=True)
    price   = models.DecimalField(max_digits=10, decimal_places=2, default=1)
   
    available = models.BooleanField(verbose_name='Disponible', default=True)
    new = models.BooleanField(verbose_name='Nouveau', default=True)
    top = models.BooleanField(verbose_name='Meilleur vente', default=True)
    created = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    photo1  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo2  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo3  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo4  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo6  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo7  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo8  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo9  = models.ImageField(upload_to='images/produits', blank=True, null=True)
    photo10 = models.ImageField(upload_to='images/produits', blank=True, null=True) 
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Produit'
        verbose_name_plural = '4. Produits'

    def get_absolute_url(self):
        return reverse("main:productDetail", args=[self.slug])

main/forms.py
from django import forms 



class MajorForm(forms.Form):
    major = forms.BooleanField(required=True)

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView
# Create your views here.
from django.db.models import Q 
from .models import SubCategory, Category, Product
from urllib.parse import unquote
from django.shortcuts import redirect
from delivery.models import Wilaya
from main.forms import MajorForm





def is_major(request):
    print('coucouuuu')
    form = MajorForm(request)
    if request.method == 'POST':
        print('OUIIIIIIIIIIIIIIIIII')
        request.session['major'] = True
        return redirect('/')


class IndexView(TemplateView):
    template_name = "index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_products"] = Product.objects.filter(new= True)
        context["top_selling"] = Product.objects.filter(top= True)
        context["random_3_1"] = Product.objects.all().order_by('?')[:3]
        context["random_3_2"] = Product.objects.all().order_by('?')[:3]
        context["random_3_3"] = Product.objects.all().order_by('?')[:3]
        context["random_3_4"] = Product.objects.all().order_by('?')[:3]
        context["random_3_5"] = Product.objects.all().order_by('?')[:3]
        context["random_3_6"] = Product.objects.all().order_by('?')[:3]
        return context
    

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = "productDetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related"] = Product.objects.all().order_by('?')[:4] 
        context["wilayas"] = Wilaya.objects.all().order_by('name') 

        return context
    



# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     sub_cat = SubCategory.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         try:
#             category = get_object_or_404(Category, slug=category_slug)
#             products = products.filter(sous_category__tree__category=category)
#         except:
#             category = get_object_or_404(SubCategory, slug=category_slug)
#             products = products.filter(sous_category=category)

#     return render(request,
#                   'catalogue.html',
#                   {'category': category,
#                    'categories': categories,
#                    'sous_categories': sub_cat,
#                    'products': products})


def new_product_list(request):
    category = None
    categories = Category.objects.all()
    sub_cat = SubCategory.objects.all()
    products = Product.objects.filter(available=True,new=True)
    return render(request,
                  'catalogue.html',{
                  'categories': categories,
                   'sous_categories': sub_cat,
                  'products': products})


class CategoryProductsView(ListView):
    context_object_name = 'products'
    model = Product
    paginate_by = 15
    template_name = "catalogue.html"

    def get_queryset(self, *args, **kwargs): # new
        
        products = Product.objects.filter(available=True)
        try:
            category = get_object_or_404(Category, slug=self.kwargs['slug'])
            products = products.filter(sous_category__tree__category=category)
        except:
            category = get_object_or_404(SubCategory, slug=self.kwargs['slug'])
            products = products.filter(sous_category=category)
        return products
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["sous_categories"] = SubCategory.objects.all()
        # context["products"] = Product.objects.all()
        return context


class ProductsView(ListView):
    context_object_name = 'products'
    model = Product
    paginate_by = 15
    template_name = "catalogue.html"

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        min = self.request.GET.get('min')
        max = self.request.GET.get('max')
        new = self.request.GET.get('new')
        top = self.request.GET.get('top')
        if max and new and top:
            products = Product.objects.filter(price__range=[min, max], available=True, new= True, top=True)
        elif max and new:
            products = Product.objects.filter(price__range=[min, max], available=True,new= True)
        elif max and top:
            products = Product.objects.filter(price__range=[min, max], available=True, top=True)
        elif top and new:
            products = Product.objects.filter(available=True,new= True, top=True)
        elif max:
            products = Product.objects.filter(price__range=[min, max], available=True)
        elif new:
            products = Product.objects.filter(available=True,new= True)
        elif top:
            products = Product.objects.filter( available=True, top=True)
        elif query:
            if len(query) > 2:
                by_2 = [query[i:i+2] for i in range(0, len(query), 2)][0]
                by_1 = [query[i:i+2] for i in range(0, len(query), 2)][1:]
                print('the sring split one  ', by_2)
                print('the sring towo', by_1)
                for i in by_1:
                    products = Product.objects.filter(
                            Q(name__icontains=by_2) & Q(name__icontains=i)
                            )
                    if not len(products):
                        products = Product.objects.filter(
                            Q(name__icontains=by_2) | Q(name__icontains=i)
                            )
                # products = Product.objects.filter(name__regex=r'(?i)dragx[\s\w]+')
                # products = Product.objects.filter(name__icontains=by_2, name__icontains=by_1)# erreur
                # products = Product.objects.filter(name__icontains=query)
                    print('JE SUISS LAAAAAA EXCEPTIO N TXwO', products)
            else: 
                products = Product.objects.filter(name__icontains=query)
        else :
            products = Product.objects.all()
        return products
    


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["sous_categories"] = SubCategory.objects.all()
        # context["products"] = Product.objects.all()
        return context

def redirect_to_shop_view(request):
    response = redirect('main:Products')
    return response

main/templates/catalogue.html
{% extends "base.html" %}
{% load static %}
{% block content %}
		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						<!-- aside Widget -->
					
					<div id="collapseFilters" >

						<div class="aside">
							<h3 class="aside-title">Filtres</h3>
							<form action="{% url 'main:Products' %}" method="get">
								<div class="input-checkbox">
									<input name="new" type="checkbox" id="category-1">
									<label for="category-1">
										<span></span>
										Nouveau
									</label>
								</div>
								<div class="input-checkbox">
									<input name="top" type="checkbox" id="category-2">
									<label for="category-2">
										<span></span>
										Meilleurs Ventes
									</label>
								</div>
							
								<div class="price-filter">
									<div id="price-slider"></div>
									<div class="input-number price-min">
										<input name="min" id="price-min" type="number">
										<span class="qty-up">+</span>
										<span class="qty-down">-</span>
									</div>
									<span>-</span>
									<div class="input-number price-max">
										<input name="max" id="price-max" type="number">
										<span class="qty-up">+</span>
										<span class="qty-down">-</span>
									</div>
								</div>
								<button class=" text-uppercase buy-directly btn-block mt-3" type="submit" style="margin-top: 8px;">Filtrer</button>
							</form>
						</div>
						<div class="aside">
							<h3 class="aside-title">Categories</h3>
							<div class="checkbox-filter">
								{% for sub in sous_categories %}
									<div class="input-checkbox">
										<a href="{{sub.get_absolute_url}}">
										<label class="text-uppercase" >
												{{sub.name}}
												<small>({{sub.products.all|length}})</small>
											</label>
										</a>
									</div>
								{% endfor %}
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						
						<!-- /aside Widget -->

						<!-- aside Widget -->
					</div>
					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store products -->
						<div class="row">
							<!-- product -->
							{% for product in products %}
								<div class="col-xs-6 col-md-4 col-xl-3">
									{% include "snippets/product-block.html" %}
								</div>
								<!-- /product -->
							{% endfor %}

					
							<!-- <div class="clearfix visible-sm visible-xs"></div> -->

							<!-- product -->
						</div>
					
						<ul class="store-pagination">
							{% if page_obj.has_previous %}
								<li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
							{% endif %}
							{% for contact in page_obj.paginator %}
								<li 
									{% if contact.number is page_obj.number %}
									class="active"
									{% endif %}
								>
								<a href="?page={{ contact.number }}" > {{ contact.number }} </a>
								</li>
							{% endfor %}
							
							{% if page_obj.has_next %}
								<!-- <a href="?page={{ page_obj.next_page_number }}">next</a> -->
								<li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
							{% endif %}
						</ul>
						<!-- store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% endblock content %}

main/templates/productDetail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb-tree">
							<li><a href="{% url 'main:IndexView' %}">Accueil</a></li>
							<li><a href="{{product.sous_category.tree.get_absolute_url}}">{{product.sous_category.tree}}</a></li>
							<li><a href="{{product.sous_category.get_absolute_url}}">{{product.sous_category}}</a></li>
							<li class="active">{{product.name}}</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- Product main img -->
					<div class="col-md-5 col-md-push-2">
						<div id="product-main-img">

							{% if product.photo1 %}
								<div class="product-preview">
									<img src="{{product.photo1.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo2 %}
								<div class="product-preview">
									<img src="{{product.photo2.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo3 %}
								<div class="product-preview">
									<img src="{{product.photo3.url}}" alt="">
								</div>			
							{% endif %}
							
							{% if product.photo4 %}
								<div class="product-preview">
									<img src="{{product.photo4.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo5 %}
								<div class="product-preview">
									<img src="{{product.photo5.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo6 %}
								<div class="product-preview">
									<img src="{{product.photo6.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo7 %}
								<div class="product-preview">
									<img src="{{product.photo7.url}}" alt="">
								</div>			
							{% endif %}
							
							{% if product.photo8 %}
								<div class="product-preview">
									<img src="{{product.photo8.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo9 %}
								<div class="product-preview">
									<img src="{{product.photo9.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo10 %}
								<div class="product-preview">
									<img src="{{product.photo10.url}}" alt="">
								</div>			
							{% endif %}
						</div>
					</div>
					<!-- /Product main img -->

					<!-- Product thumb imgs -->
					<div class="col-md-2  col-md-pull-5">
						<div id="product-imgs">
							{% if product.photo1 %}
								<div class="product-preview">
									<img src="{{product.photo1.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo2 %}
								<div class="product-preview">
									<img src="{{product.photo2.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo3 %}
								<div class="product-preview">
									<img src="{{product.photo3.url}}" alt="">
								</div>
							{% endif %}
							
							{% if product.photo4 %}
								<div class="product-preview">
									<img src="{{product.photo4.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo5 %}
								<div class="product-preview">
									<img src="{{product.photo5.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo6 %}
								<div class="product-preview">
									<img src="{{product.photo6.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo7 %}
								<div class="product-preview">
									<img src="{{product.photo7.url}}" alt="">
								</div>			
							{% endif %}
							
							{% if product.photo8 %}
								<div class="product-preview">
									<img src="{{product.photo8.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo9 %}
								<div class="product-preview">
									<img src="{{product.photo9.url}}" alt="">
								</div>
							{% endif %}

							{% if product.photo10 %}
								<div class="product-preview">
									<img src="{{product.photo10.url}}" alt="">
								</div>			
							{% endif %}
						</div>
					</div>
					<!-- /Product thumb imgs -->

					<!-- Product details -->
					<div class="col-md-5">
						<div class="product-details">
							<h2 class="product-name">{{product.name}}</h2>
							<ul class="product-links">
								<li>Categorie:</li>
								<li><a href="{{product.sous_category.get_absolute_url}}">{{product.sous_category}}</a></li>
							</ul>
							<div>
								<h3 class="product-price">{{product.price}}  DZD</h3>
								<span class="product-available">
									{% if product.available %}
										Disponible
									{% else %}
										En Rupture 
									{% endif %}
								</span>
							</div>
							
							{% if product.available %}
							<form action="{% url 'order:cart_add' product.id %}" method="POST" >
								{% csrf_token %}
								<div class="add-to-cart">
									<div class="qty-label">
										Qty
										<div class="input-number">
											<input type="number" name="quantity" value="1">
											<span class="qty-up">+</span>
											<span class="qty-down">-</span>
										</div>
									</div>
									<button type="submit" class=" btn text-uppercase add-to-cart-btn">
											<i class="fa fa-shopping-cart"></i>
											<span class="tooltipp">Ajouter au panier</span>
									</button>
								</div>
							</form>

							<div class="billing-details">
								<a class=" btn h3 buy-directly" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
									Acheter directement
								</a>
							</div>
							{% endif %}
								<div class="collapse"  id="collapseExample">
									<form id="order_form"  method="post" action="{% url 'order:order_create_one_product' product.id %}" data-communes-url="{% url 'delivery:load_communes' %}">
									{% csrf_token %}
										<div class="form-group">
											<input class="input" type="text" name="first_name" placeholder="nom (اللقب)">
										</div>
										<div class="form-group">
											<input class="input" type="text" name="last_name" placeholder="prenom (الاسم)">
										</div>
										<div class="form-group">
											<input class="input" type="text" name="addresse"placeholder="addresse ( العنوان)">
										</div>
										<div class="form-group">
											<input class="input" type="email" name="email" placeholder="Email">
										</div>
										<div class="form-group">
											<select class="input" name="wilaya" id="wilayaId"  required>
												<option class="option" value='' selected>Wilaya ( الولاية)</option>
												{% for wilaya in wilayas %}
													<option class="option" value={{wilaya.id}}>{{wilaya.name}}</option>
												{% endfor %}
											</select>
										</div>
										<div class="form-group">
											<select class="input" name="commune" id="communesId" required>
												<option class="option" value='' selected>Commune (البلدية)</option>
												{% for commune in communes %}
													<option class="option" value={{commune.id}}>{{commune.name}}</option>
												{% endfor %}
											</select>
										</div>
										<div class="form-group">
											<input class="input" type="tel" name="phone" placeholder="Téléphone (رقم الهاتف)">
										</div>
										<div class="form-group">
											<label for="birth_date">date de naissance (تاريخ الميلاد)</label>
											<input class="input" type="date" name="birth_date" placeholder="date de naissance (تاريخ الميلاد)">
										</div>
										<div class="form-group">
											<input id="hiddenQte" class="input" type="number"value="1" hidden name="quantity">
										</div>
										<div class="add-to-cart">
											<button type="submit" class="add-to-cart-btn">Confirmer l'achat</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- /Product details -->
					<!-- Product tab -->
					{% if product.description %}
						<div class="col-md-12">
							<div id="product-tab">
								<ul class="tab-nav">
									<li class="active"><a  href="#product-tab">Déscription</a></li>
								</ul>
								<div class="tab-content">
									<div id="tab1" class="tab-pane fade in active">
										<div class="row">
											<div class="col-md-12">
												<p>{{product.description|safe}}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endif %}
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
		<!-- Section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="section-title text-center">
							<h3 class="title">Related Products</h3>
						</div>
					</div>
					{% for product in related %}
						<div class="col-md-3 col-xs-6">
							{% include "snippets/product-block.html" %}
						</div>
					{% endfor %}
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /Section -->

{% endblock content %}